addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.5.3")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"           % "2.0.14")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.14.4")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.10.4")
