version = 3.10.1
runner.dialect = scala213

style = defaultWithAlign
maxColumn = 120
danglingParentheses.preset = true
binPack.parentConstructors = false
align {
  openParenCallSite                      = false
  tokens                                 = ["%", "%%", {code = "=>", owner = "Case"}, {code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))"}, ]
  arrowEnumeratorGenerator               = true
}
newlines {
  implicitParamListModifierForce = [before, after]
}
project {
  excludeFilters = [ .scalafmt.conf ]
  git = true
}
rewrite.rules = [PreferCurlyFors, RedundantBraces, RedundantParens]
spaces.inImportCurlyBraces = true
