services:

  forex-app:
    image: forex:1.0.1
    container_name: forex-app
    ports:
      - "8081:8081"
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8081
      - REDIS_URI=redis://redis:6379
      - ONEFRAME_BASE_URI=http://oneframe:8080
    depends_on:
      - redis
      - oneframe
    networks:
      - forex-network
    profiles:
      - full
      - load-test

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - forex-network
    profiles:
      - full
      - dev
      - load-test

  oneframe:
    image: paidyinc/one-frame:latest
    container_name: oneframe
    ports:
      - "8080:8080"
    networks:
      - forex-network
    ulimits:
      nofile: 65536
    profiles:
      - full
      - dev
      - load-test

  k6:
    image: grafana/k6
    container_name: k6
    depends_on:
      - forex-app
    environment:
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_PERIOD=5s
      - K6_SUMMARY_MODE=full
    ports:
      - "6565:6565"
      - "5665:5665"
    networks:
      - forex-network
    volumes:
      - ./load-tests/rates.js:/tests/rates.js
    entrypoint: ["k6", "run", "/tests/rates.js"]
    profiles:
      - load-test

volumes:
  redis_data:

networks:
  forex-network:
    driver: bridge
