app {
  http {
    host = "0.0.0.0"
    port = 8081
    timeout = 40 seconds
  }
  redis {
    uri = "redis://localhost"
  }
  rates {
    program.cache-ttl = 5 minutes
    oneFrame {
      base-uri = "localhost:8080"
      token = "10dc303535874aeccc86a8251e6992f5"
      ratesPath = "/rates"
    }
  }
}

