app {
  http {
    host = "0.0.0.0"
    host = ${?HTTP_HOST}
    port = 8081
    port = ${?HTTP_PORT}
    timeout = 40 seconds
    timeout = ${?HTTP_TIMEOUT}
  }
  redis {
    uri = "redis://localhost:6379"
    uri = ${?REDIS_URI}
  }
  rates {
    program.cache-ttl = 5 minutes
    program.cache-ttl = ${?RATES_CACHE_TTL}
    oneframe {
      base-uri = "localhost:8080"
      base-uri = ${?ONEFRAME_BASE_URI}
      token = "10dc303535874aeccc86a8251e6992f5"
      token = ${?ONEFRAME_TOKEN}
      rates-path = "/rates"
      rates-path = ${?ONEFRAME_RATES_PATH}
    }
  }
}

