app {
  http {
    host = "0.0.0.0"
    host = ${?HTTP_HOST}
    port = 8081
    port = ${?HTTP_PORT}
    timeout = 40 seconds
    timeout = ${?HTTP_TIMEOUT}
  }

  redis {
    uri = "redis://localhost:6379"
    uri = ${?REDIS_URI}
  }

  rates {
    program {
      rates-polling-timeout: 4 minute
      rates-polling-timeout = ${?RATES_POLLING_TIMEOUT}
      currencies: [
        "USD", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "NZD", "SGD" 
      ]
    }

    oneframe {
      base-uri = "http://localhost:8080"
      base-uri = ${?ONEFRAME_BASE_URI}
      token = "10dc303535874aeccc86a8251e6992f5"
      token = ${?ONEFRAME_TOKEN}
      rates-path = "/rates"
      rates-path = ${?ONEFRAME_RATES_PATH}

      get-retry {
        is-enabled = true
        is-enabled = ${?ONEFRAME_GET_RETRY_IS_ENABLED}
        max-retries = 5
        max-retries = ${?ONEFRAME_GET_RETRY_MAX_RETRIES}
        base-delay = 1 second
        base-delay = ${?ONEFRAME_GET_RETRY_BASE_DELAY}
      }

      get-batch-retry {
        is-enabled = true
        is-enabled = ${?ONEFRAME_GET_BATCH_RETRY_IS_ENABLED}
        max-retries = 5
        max-retries = ${?ONEFRAME_GET_BATCH_RETRY_MAX_RETRIES}
        base-delay = 1 second
        base-delay = ${?ONEFRAME_GET_BATCH_RETRY_BASE_DELAY}
      }
    }

    cache {
      rates-namespace: "rates"
      rates-namespace: ${?RATES_CACHE_NAMESPACE}
      rates-lock-namespace: "rates-lock"
      rates-lock-namespace: ${?RATES_CACHE_LOCK_NAMESPACE}
      lock-key: "lock"
      lock-key: ${?RATES_CACHE_LOCK_KEY}
      lock-ttl: 4 minute
      lock-ttl: ${?RATES_CACHE_LOCK_TTL}

      get-retry {
        is-enabled = true
        is-enabled = ${?RATES_CACHE_GET_RETRY_IS_ENABLED}
        max-retries = 3
        max-retries = ${?RATES_CACHE_GET_RETRY_MAX_RETRIES}
        base-delay = 250 millis
        base-delay = ${?RATES_CACHE_GET_RETRY_BASE_DELAY}
      }

      set-all-retry {
        is-enabled = true
        is-enabled = ${?RATES_CACHE_SET_ALL_RETRY_IS_ENABLED}
        max-retries = 5
        max-retries = ${?RATES_CACHE_SET_ALL_RETRY_MAX_RETRIES}
        base-delay = 1 second
        base-delay = ${?RATES_CACHE_SET_ALL_RETRY_BASE_DELAY}
      }

      try-acquire-retry {
        is-enabled = true
        is-enabled = ${?RATES_CACHE_TRY_ACQUIRE_RETRY_IS_ENABLED}
        max-retries = 5
        max-retries = ${?RATES_CACHE_TRY_ACQUIRE_RETRY_MAX_RETRIES}
        base-delay = 1 second
        base-delay = ${?RATES_CACHE_TRY_ACQUIRE_RETRY_BASE_DELAY}
      }
    }
  }
}

